# Generated by Django 4.2.6 on 2023-10-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='case_number')),
                ('case_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='case_status')),
                ('case_submitted', models.DateField(blank=True, null=True, verbose_name='case_submitted')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='decision_date')),
                ('visa_class', models.CharField(blank=True, max_length=10, null=True, verbose_name='visa_class')),
                ('employment_start_date', models.DateField(blank=True, null=True, verbose_name='employment_start_date')),
                ('employment_end_date', models.DateField(blank=True, null=True, verbose_name='employment_end_date')),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='employer_name')),
                ('employer_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='employer_address')),
                ('employer_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_city')),
                ('employer_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='employer_state')),
                ('employer_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='employer_postal_code')),
                ('employer_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_country')),
                ('employer_province', models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_province')),
                ('employer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='employer_phone')),
                ('employer_phone_ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='employer_phone_ext')),
                ('agent_attorney_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='agent_attorney_name')),
                ('agent_attorney_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='agent_attorney_city')),
                ('agent_attorney_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='agent_attorney_state')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='job_title')),
                ('soc_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='soc_code')),
                ('soc_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='soc_name')),
                ('naic_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='naic_code')),
                ('total_workers', models.IntegerField(blank=True, null=True, verbose_name='total_workers')),
                ('full_time_position', models.CharField(blank=True, null=True, verbose_name='full_time_position')),
                ('prevailing_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prevailing_wage')),
                ('pw_unit_of_pay', models.CharField(blank=True, max_length=10, null=True, verbose_name='pw_unit_of_pay')),
                ('pw_wage_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='pw_wage_source')),
                ('pw_source_year', models.IntegerField(blank=True, null=True, verbose_name='pw_source_year')),
                ('pw_source_other', models.CharField(blank=True, max_length=255, null=True, verbose_name='pw_source_other')),
                ('wage_rate_of_pay_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='wage_rate_of_pay_from')),
                ('wage_rate_of_pay_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='wage_rate_of_pay_to')),
                ('wage_unit_of_pay', models.CharField(blank=True, max_length=10, null=True, verbose_name='wage_unit_of_pay')),
                ('h1b_dependent', models.CharField(blank=True, max_length=1, null=True, verbose_name='h1b_dependent')),
                ('willful_violator', models.CharField(blank=True, max_length=1, null=True, verbose_name='willful_violator')),
                ('worksite_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='worksite_city')),
                ('worksite_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='worksite_county')),
                ('worksite_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='worksite_state')),
                ('worksite_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='worksite_postal_code')),
                ('original_cert_date', models.DateField(blank=True, null=True, verbose_name='original_cert_date')),
            ],
        ),
    ]
