# Generated by Django 4.2.6 on 2023-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer_phone_ext',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_phone_ext'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='naic_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='naic_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pw_unit_of_pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pw_unit_of_pay'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='soc_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='soc_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visa_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='visa_class'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_unit_of_pay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='wage_unit_of_pay'),
        ),
    ]
