# Generated by Django 4.2.6 on 2023-10-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_full_time_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='h1b_dependent',
            field=models.CharField(max_length=1, verbose_name='h-1b_dependent'),
        ),
    ]
