# Generated by Django 4.2.6 on 2023-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_h1b_dependent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='agent_attorney_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='agent_attorney_city'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agent_attorney_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='agent_attorney_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='agent_attorney_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='agent_attorney_state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='case_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='case_number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='case_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='case_status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='case_submitted',
            field=models.DateField(blank=True, null=True, verbose_name='case_submitted'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='decision_date',
            field=models.DateField(blank=True, null=True, verbose_name='decision_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='employer_address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_city'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='employer_country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='employer_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='employer_phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='employer_postal_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='employer_state'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='employment_end_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='employment_start_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_time_position',
            field=models.CharField(blank=True, null=True, verbose_name='full_time_position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='h1b_dependent',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='h1b_dependent'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='job_title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='naic_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='naic_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='original_cert_date',
            field=models.DateField(blank=True, null=True, verbose_name='original_cert_date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='prevailing_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prevailing_wage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pw_source_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='pw_source_year'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pw_unit_of_pay',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='pw_unit_of_pay'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pw_wage_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pw_wage_source'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='soc_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='soc_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='soc_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='soc_name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_workers',
            field=models.IntegerField(blank=True, null=True, verbose_name='total_workers'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visa_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='visa_class'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_rate_of_pay_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='wage_rate_of_pay_from'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_rate_of_pay_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='wage_rate_of_pay_to'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage_unit_of_pay',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='wage_unit_of_pay'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='willful_violator',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='willful_violator'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksite_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='worksite_city'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksite_county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='worksite_county'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksite_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='worksite_postal_code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='worksite_state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='worksite_state'),
        ),
    ]
